version = 0.1
[jf-dev]
[jf-dev.deploy]
[jf-dev.deploy.parameters]
stack_name = "jf-dev-subscription-function-stack"
s3_bucket = "lambda-deployables-lds-us-east-1"
s3_prefix = "subscription-function"
region = "us-east-1"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
disable_rollback = false
image_repositories = []
parameter_overrides= 'VersionId=versionId StackNamespace=jf StackRegion=us-east-1 StackEnv=dev ApiGatewayStack=jf-dev-lds-api-gateway VpcStack=jf-dev-lds-vpc ApiGatewayStack:si-dev-lds-api-gateway KinesisStack=jf-dev-lds-kinesis RedisStack=jf-dev-lds-elasticache-redis SecurityGroupStack=jf-dev-lds-client-sg'
